### ISSUE TITLE
cEOS64-lab-4.28.0F not available, cEOS not available to guests, only vEOS

### ISSUE THREAD

**Issue by jnaky4** [PacktPublishing/Network-Automation-with-Go#8]
This training environment setup is minimally written about setting up with Arista. Not only can you not download any of the cEOS packages as a guest,  the image required doesnt exists.

**Comment by nleiva** [comment]
Hi @jnaky4,

It's out of our control what images Arista continues to host on their website. If you follow the instructions on [cEOS image](https://github.com/PacktPublishing/Network-Automation-with-Go/blob/main/ch12/testbed/get_arista_ceos.md), you'll find cEOS-4.28.7M to download.

![image](https://github.com/PacktPublishing/Network-Automation-with-Go/assets/8928883/5065a49e-c399-4df0-be0b-d4e79ab5b40b)

After you extract/upload the image, import it with this command: `docker import cEOS64-lab-4.28.7M.tar ceos:4.28`. The last part is key (`ceos:4.28`), is the tag we reference in the topology files:

https://github.com/PacktPublishing/Network-Automation-with-Go/blob/main/topo-base/topo.yml -> `image: ceos:4.28`
```yaml
name: netgo

topology:
  nodes:
    srl:
      kind: srl
      image: ghcr.io/nokia/srlinux:21.6.4
    ceos:
      kind: ceos
      image: ceos:4.28
      startup-config: ceos-startup
      binds:
      - secure/ssl:/persist/secure/ssl
    cvx:
      kind: cvx
      image: networkop/cx:5.0.0
      runtime: docker

  links:
    - endpoints: ["srl:e1-1", "ceos:eth1"]
    - endpoints: ["cvx:swp1", "ceos:eth2"]
```

Let me know if this doesn't work for you.
